"""Ep 11 — Search.

Scene spec for video/build.py.

Every query result here is from a real run against the database search
backend, including the private-page leak (tested in a rolled-back
transaction). See notes.md.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VIDEO = HERE.parent.parent / "video"
sys.path.insert(0, str(VIDEO))
from build import Episode, Scene  # noqa: E402
from term import Cmd, terminal_scene  # noqa: E402

BADGE = 'WAGTAIL <b>UNBOXED</b> &nbsp;&middot;&nbsp; 11'
VENV = "(.venv) PS&gt;"
PY = "&gt;&gt;&gt;"

SHOT_SEARCH = (HERE / "assets" / "shot-search.png").as_uri()
SHOT_PRIYA = (HERE / "assets" / "shot-priya.png").as_uri()

SHOT_CSS = """
<style>
.shot { border: 2px solid var(--line); border-radius: 14px; overflow: hidden;
        box-shadow: 0 30px 70px rgba(0,0,0,.45); margin: 0 auto; }
.shot img { display: block; width: 100%; }
.shotbar { background: #161925; padding: 14px 22px; font-family: var(--mono);
           font-size: 24px; color: var(--muted); border-bottom: 2px solid var(--line); }
</style>
"""


def shot(url_label: str, src: str, width: str) -> str:
    return (SHOT_CSS +
            f'<div class="shot" style="width:{width}"><div class="shotbar">{url_label}</div>'
            f'<img src="{src}" alt=""></div>')


EPISODE = Episode(
    key="ep11",
    number="11",
    title="Ep 11 - Search",
    badge=BADGE,
    intro_say="Search.",
    outro_say="Next episode, the editor experience. Thanks for watching.",
    scenes=[
        Scene(
            id="unboxed",
            body="""
            <div class="eyebrow">Unboxed in episode 2, untouched since</div>
            <h2>The search/ app</h2>
            <div class="sub" style="margin-top:36px">A view, a template and a URL, generated by
            <b>wagtail start</b>. It works out of the box. Today we find four ways it doesn't
            work <b>well</b>.</div>
            """,
            say="Back in episode two we unboxed an app called search. A view, a template and a U R L, "
                "all generated for us, and untouched ever since. It does work out of the box. Today "
                "we find four ways it does not work well.",
        ),
        terminal_scene(
            scene_id="titles_only",
            eyebrow="Out of the box",
            title="",
            bar="Page.objects.live().search(q)",
            steps=[
                Cmd(text="search('pricing')        # in a title", out="1 result", prompt=PY, highlight=["1"]),
                Cmd(text="search('fixed price')    # in an intro", out="0 results", prompt=PY, error=["0"]),
                Cmd(text="search('integrations')   # in a body", out="0 results", prompt=PY, error=["0"]),
            ],
            say="Search for a word in a post's title, and it is found. A phrase from the intro. Nothing. "
                "A word from the body. Nothing.",
        ),
        Scene(
            id="search_fields",
            body="""
            <div class="filename">blog/models.py</div>
            <pre class="code" style="font-size:30px"><span class="k">from</span> wagtail.search <span class="k">import</span> index

search_fields = Page.search_fields + [
    index.<span class="k">SearchField</span>(<span class="s">"intro"</span>),
    index.<span class="k">SearchField</span>(<span class="s">"body"</span>),
    index.<span class="k">FilterField</span>(<span class="s">"date"</span>),
]</pre>
            <div class="sub" style="margin-top:30px"><b>Page.search_fields</b> is the title and some
            filters. Every other field has to be named. No migration &mdash; <b>No changes detected</b>.</div>
            """,
            say="Because the page class only indexes the title. Every other field has to be named in "
                "search fields. Intro and body as search fields, and the date as a filter field for "
                "later. It is not a schema change, so there is no migration.",
        ),
        terminal_scene(
            scene_id="still_nothing",
            eyebrow="Fields added. Search again.",
            title="",
            bar="Page.objects.live().search(q)",
            steps=[
                Cmd(text="search('fixed price')", out="0 results", prompt=PY, error=["0"]),
                Cmd(text="search('integrations')", out="0 results", prompt=PY, error=["0"]),
            ],
            say="Fields added. Search again. Still nothing.",
        ),
        terminal_scene(
            scene_id="update_index",
            eyebrow="The index is what was written at save time",
            title="",
            bar="(.venv) &nbsp;&middot;&nbsp; PowerShell",
            steps=[
                Cmd(text="python manage.py update_index",
                    out="default: blog.BlogPage             .\ndefault: indexed 19 objects",
                    prompt=VENV, highlight=["indexed"]),
                Cmd(text="# search('fixed price')", out="1 result", prompt=VENV, highlight=["1"]),
            ],
            say="The search index holds whatever was written when each page was last saved, and "
                "changing search fields does not rewrite it. Update index rebuilds it. Nineteen "
                "objects. And now the intro is found. From here on, publishing a page reindexes it "
                "automatically.",
        ),

        # ------------------------------------------------------- snippets
        Scene(
            id="visible_not_found",
            body="""
            <div class="eyebrow">On the page, but not in the index</div>
            <table>
              <tr><td class="k">'Priya'</td><td class="v">visible on /about/ &mdash; search finds <span style="color:var(--red)">nothing</span></td></tr>
              <tr><td class="k">'Moreau'</td><td class="v">visible on / &mdash; search finds <span style="color:var(--red)">nothing</span></td></tr>
            </table>
            <div class="sub" style="margin-top:32px">The team block fetches names at render time. The
            testimonial block stores an <b>id</b>. Neither text is part of the page when it's indexed.</div>
            """,
            say="Now try a team member's name. Priya is right there on the About page. Search finds "
                "nothing. Same for the testimonial on the home page. The team block fetches its names "
                "when the page renders, and the testimonial block only stores an id. So when the page "
                "is indexed, that text simply is not part of it.",
        ),
        Scene(
            id="searchable_content",
            body="""
            <div class="filename">home/blocks.py</div>
            <pre class="code" style="font-size:28px"><span class="k">class</span> TestimonialBlock(blocks.StructBlock):
    &hellip;
    <span class="k">def</span> get_searchable_content(self, value):
        t = value.get(<span class="s">"testimonial"</span>)
        <span class="k">return</span> [t.quote, t.author, t.company] <span class="k">if</span> t <span class="k">else</span> []</pre>
            <div class="sub" style="margin-top:30px">Same on TeamBlock. After <b>update_index</b>:
            Priya &rarr; About, Moreau &rarr; Home.<br><br>
            The trade-off: those words are <b>copied</b> into the page's entry. Change the team, and
            About is stale until it's saved again.</div>
            """,
            say="Blocks have a method for exactly this. Get searchable content returns the words that "
                "should be indexed for this block. Return the quote and the author, do the same for "
                "the team, reindex, and now Priya finds the About page. The honest trade off. Those "
                "words are copied into the page's index entry, so if the team changes, the About page "
                "is stale until someone saves it or you run update index.",
        ),

        # ------------------------------------------------------- private pages
        terminal_scene(
            scene_id="private_leak",
            eyebrow="Password-protect a post, then search",
            title="",
            bar="inside a rolled-back transaction",
            steps=[
                Cmd(text=".live().search('pricing')",
                    out="['Pricing a website honestly']", prompt=PY, error=["Pricing"]),
                Cmd(text=".live().public().search('pricing')",
                    out="[]", prompt=PY, highlight=["[]"]),
            ],
            say="And this one matters. I password protected the pricing post and searched. The query "
                "in the generated view still returns it. Add public, and it does not.",
        ),
        Scene(
            id="private_why",
            body="""
            <h2>The generated view shows private pages</h2>
            <div class="sub" style="margin-top:28px"><b>wagtail start</b> writes
            <b>Page.objects.live().search()</b>. Live means published &mdash; not visible to
            everybody. The <b>title</b> of every password-protected or login-only page appears in
            results for anyone.</div>
            <pre class="code" style="font-size:31px;margin-top:32px">Page.objects.live()<span class="k">.public()</span>.specific().search(q)</pre>
            """,
            say="The view that Wagtail generates uses live, and live means published. It does not mean "
                "visible to everyone. So the title of every private page on your site shows up in "
                "search results for any visitor. Add public. And add specific while you are there, "
                "so each result is its real page type and can show its intro.",
        ),
        Scene(
            id="view",
            body="""
            <div class="filename">search/views.py</div>
            <pre class="code" style="font-size:27px">search_query = request.GET.get(<span class="s">"query"</span>, <span class="s">""</span>).strip()
<span class="k">if</span> search_query:
    results = Page.objects.live().public().specific().search(search_query)
<span class="k">else</span>:
    results = Page.objects.none()

paginator = Paginator(results, <span class="s">10</span>)
results_page = paginator.<span class="k">get_page</span>(request.GET.get(<span class="s">"page"</span>))</pre>
            <div class="sub" style="margin-top:26px">And <b>get_page</b>, for the same reason as the
            journal in episode 7.</div>
            """,
            say="So the view becomes this. Strip the query, search only public live pages as their "
                "specific types, and paginate with get page, exactly like the journal in episode seven.",
        ),
        Scene(
            id="template",
            body="""
            <h2>The results template</h2>
            <table>
              <tr><td class="k">a labelled input</td><td class="v">type="search", label hidden visually, not from screen readers</td></tr>
              <tr><td class="k">a count</td><td class="v">9 results for <b>handover</b></td></tr>
              <tr><td class="k">each result</td><td class="v">its page type, title and intro</td></tr>
              <tr><td class="k">pagination</td><td class="v">carries <b>?query=</b> &mdash; episode 8's lesson</td></tr>
            </table>
            """,
            say="The template gets a properly labelled search box, a result count, each result's page "
                "type, title and intro, and pagination links that carry the query along, which is the "
                "lesson from episode eight.",
        ),

        # ------------------------------------------------------- payoff
        Scene(
            id="after_search",
            body=f"""
            <div class="eyebrow">Search is in the menu now</div>
            {shot("localhost:8000/search/?query=handover", SHOT_SEARCH, "60%")}
            """,
            say="And here it is, with search in the menu. Handover finds nine pages, across three page "
                "types.",
        ),
        Scene(
            id="after_priya",
            body=f"""
            <div class="eyebrow">A name that only lives in a snippet</div>
            {shot("localhost:8000/search/?query=Priya", SHOT_PRIYA, "60%")}
            """,
            say="And a team member's name, which only lives in a snippet, now finds the About page.",
        ),
        terminal_scene(
            scene_id="commit",
            eyebrow="Checkpoint",
            title="",
            bar="(.venv) &nbsp;&middot;&nbsp; PowerShell",
            steps=[
                Cmd(text="git add -A", prompt=VENV),
                Cmd(text='git commit -m "episode 11"', prompt=VENV),
                Cmd(text="git tag ep11-end", prompt=VENV),
            ],
            say="Commit, and tag.",
        ),
        Scene(
            id="next",
            body="""
            <div class="eyebrow">Next &mdash; Act 3</div>
            <h2>Ep 12 &mdash; Editor Experience Polish</h2>
            <div class="sub" style="margin-top:36px">The site is feature-complete. Now we make the
            admin pleasant for the client who has to use it.</div>
            """,
            say="And with that, the site is feature complete. Next episode starts the final act. "
                "Making the admin pleasant for the client who actually has to use it.",
        ),
    ],
)
