# Generated by Django 6.1.1 on 2026-09-20 04:44
#
# Hand-edited: the AlterField alone fails on any page that already has
# rich-text content, because the new column is JSON and "<p>...</p>" is not
# valid JSON. The RunPython below rewraps the old HTML first, while the
# column is still plain text.

import json
import uuid

import wagtail.fields
from django.db import migrations

MODELS = ("HomePage", "StandardPage")


def html_to_stream(apps, schema_editor):
    """Rewrap each page's rich-text HTML as one 'paragraph' block."""
    for model_name in MODELS:
        Model = apps.get_model("home", model_name)
        for page in Model.objects.all():
            html = (page.body or "").strip()
            if html.startswith("["):
                continue  # already StreamField JSON
            blocks = (
                [{"type": "paragraph", "value": html, "id": str(uuid.uuid4())}]
                if html
                else []
            )
            Model.objects.filter(pk=page.pk).update(body=json.dumps(blocks))


def stream_to_html(apps, schema_editor):
    """Reverse: flatten paragraph blocks back to a single HTML string."""
    for model_name in MODELS:
        Model = apps.get_model("home", model_name)
        for page in Model.objects.all():
            try:
                blocks = json.loads(page.body or "[]")
            except (TypeError, ValueError):
                continue
            html = "".join(
                b.get("value", "") for b in blocks if b.get("type") == "paragraph"
            )
            Model.objects.filter(pk=page.pk).update(body=html)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_standardpage_homepage_body_homepage_intro'),
    ]

    operations = [
        migrations.RunPython(html_to_stream, stream_to_html),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('quote', 4), ('services', 9), ('cta', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'home/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'icon': 'pilcrow'}), 2: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it. Leave blank for an unattributed quote.', 'max_length': 120, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('quote', 2), ('attribution', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'What we do', 'max_length': 80}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 7: ('wagtail.blocks.StructBlock', [[('name', 6), ('description', 2)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 6, 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('heading', 5), ('services', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'The line above the button.', 'max_length': 120}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 40}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page on this site. Takes priority over the URL below.', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 10), ('button_text', 11), ('page', 12), ('external_url', 13)]], {})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('quote', 4), ('services', 9), ('cta', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'home/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'icon': 'pilcrow'}), 2: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it. Leave blank for an unattributed quote.', 'max_length': 120, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('quote', 2), ('attribution', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'default': 'What we do', 'max_length': 80}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 7: ('wagtail.blocks.StructBlock', [[('name', 6), ('description', 2)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 6, 'min_num': 1}), 9: ('wagtail.blocks.StructBlock', [[('heading', 5), ('services', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'The line above the button.', 'max_length': 120}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 40}), 12: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page on this site. Takes priority over the URL below.', 'required': False}), 13: ('wagtail.blocks.URLBlock', (), {'required': False}), 14: ('wagtail.blocks.StructBlock', [[('text', 10), ('button_text', 11), ('page', 12), ('external_url', 13)]], {})}),
        ),
    ]
