# Generated by Django 6.1.1 on 2026-09-20 05:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body_alter_standardpage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_alt',
            field=models.CharField(blank=True, help_text='What the image shows, for screen readers. Leave blank only if the image is purely decorative.', max_length=180, verbose_name='Hero alt text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_caption',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Shown full width above the page title. Landscape works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hero_alt',
            field=models.CharField(blank=True, help_text='What the image shows, for screen readers. Leave blank only if the image is purely decorative.', max_length=180, verbose_name='Hero alt text'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hero_caption',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Shown full width above the page title. Landscape works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 8), ('services', 13), ('download', 16), ('cta', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'home/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text width'), ('wide', 'Full width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('width', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it. Leave blank for an unattributed quote.', 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'What we do', 'max_length': 80}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 11: ('wagtail.blocks.StructBlock', [[('name', 10), ('description', 6)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 6, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('heading', 9), ('services', 12)]], {}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Defaults to the document's own title.", 'max_length': 120, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('document', 14), ('title', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'The line above the button.', 'max_length': 120}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 40}), 19: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page on this site. Takes priority over the URL below.', 'required': False}), 20: ('wagtail.blocks.URLBlock', (), {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 17), ('button_text', 18), ('page', 19), ('external_url', 20)]], {})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 8), ('services', 13), ('download', 16), ('cta', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'home/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text width'), ('wide', 'Full width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('width', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it. Leave blank for an unattributed quote.', 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'What we do', 'max_length': 80}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 11: ('wagtail.blocks.StructBlock', [[('name', 10), ('description', 6)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 6, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('heading', 9), ('services', 12)]], {}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Defaults to the document's own title.", 'max_length': 120, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('document', 14), ('title', 15)]], {}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'The line above the button.', 'max_length': 120}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 40}), 19: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page on this site. Takes priority over the URL below.', 'required': False}), 20: ('wagtail.blocks.URLBlock', (), {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('text', 17), ('button_text', 18), ('page', 19), ('external_url', 20)]], {})}),
        ),
    ]
