# Generated by Django 6.1.1 on 2026-09-21 08:16

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_alt_homepage_hero_caption_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=400)),
                ('author', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 8), ('services', 13), ('download', 16), ('testimonial', 18), ('team', 20), ('cta', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'home/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text width'), ('wide', 'Full width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('width', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it. Leave blank for an unattributed quote.', 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'What we do', 'max_length': 80}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 11: ('wagtail.blocks.StructBlock', [[('name', 10), ('description', 6)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 6, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('heading', 9), ('services', 12)]], {}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Defaults to the document's own title.", 'max_length': 120, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('document', 14), ('title', 15)]], {}), 17: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Testimonial',), {}), 18: ('wagtail.blocks.StructBlock', [[('testimonial', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'The team', 'max_length': 80}), 20: ('wagtail.blocks.StructBlock', [[('heading', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'The line above the button.', 'max_length': 120}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 40}), 23: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page on this site. Takes priority over the URL below.', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('text', 21), ('button_text', 22), ('page', 23), ('external_url', 24)]], {})}),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 8), ('services', 13), ('download', 16), ('testimonial', 18), ('team', 20), ('cta', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'home/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text width'), ('wide', 'Full width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('width', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it. Leave blank for an unattributed quote.', 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'What we do', 'max_length': 80}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 11: ('wagtail.blocks.StructBlock', [[('name', 10), ('description', 6)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 6, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('heading', 9), ('services', 12)]], {}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Defaults to the document's own title.", 'max_length': 120, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('document', 14), ('title', 15)]], {}), 17: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Testimonial',), {}), 18: ('wagtail.blocks.StructBlock', [[('testimonial', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'The team', 'max_length': 80}), 20: ('wagtail.blocks.StructBlock', [[('heading', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'The line above the button.', 'max_length': 120}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 40}), 23: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page on this site. Takes priority over the URL below.', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('text', 21), ('button_text', 22), ('page', 23), ('external_url', 24)]], {})}),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'team member',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
