# Generated by Django 6.1.1 on 2026-09-21 08:16

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 8), ('services', 13), ('download', 16), ('testimonial', 18), ('team', 20), ('cta', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'template': 'home/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'document-link'], 'icon': 'pilcrow'}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 180, 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text width'), ('wide', 'Full width')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('width', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {'rows': 3}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'Who said it. Leave blank for an unattributed quote.', 'max_length': 120, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('quote', 6), ('attribution', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'What we do', 'max_length': 80}), 10: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 11: ('wagtail.blocks.StructBlock', [[('name', 10), ('description', 6)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'max_num': 6, 'min_num': 1}), 13: ('wagtail.blocks.StructBlock', [[('heading', 9), ('services', 12)]], {}), 14: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': "Defaults to the document's own title.", 'max_length': 120, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('document', 14), ('title', 15)]], {}), 17: ('wagtail.snippets.blocks.SnippetChooserBlock', ('home.Testimonial',), {}), 18: ('wagtail.blocks.StructBlock', [[('testimonial', 17)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'The team', 'max_length': 80}), 20: ('wagtail.blocks.StructBlock', [[('heading', 19)]], {}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'The line above the button.', 'max_length': 120}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Get in touch', 'max_length': 40}), 23: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'A page on this site. Takes priority over the URL below.', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'required': False}), 25: ('wagtail.blocks.StructBlock', [[('text', 21), ('button_text', 22), ('page', 23), ('external_url', 24)]], {})}),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
